# Generated by Django 5.1.5 on 2025-01-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_like_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
